export const solutions = [
 {slug:'asset-tracking', title:'Asset tracking & RTLS', short:'Find the asset. Understand the movement.', description:'Bring location and movement into the operational picture, from equipment within a facility to assets moving between sites.', icon:'location', points:['Asset identity and location history','Site and zone-based visibility','Movement events and workflow design'], question:'Which assets need visibility, and how precise does their location need to be?'},
 {slug:'remote-monitoring', title:'Remote monitoring', short:'Stay closer to conditions on the ground.', description:'Plan monitoring around the measurements that matter: temperature, humidity, equipment state and other operational signals.', icon:'signal', points:['Sensor and gateway selection','Condition dashboards and trend views','Agreed alert and response workflows'], question:'Which condition changes require action, and who needs to know?'},
 {slug:'cold-chain', title:'Cold chain intelligence', short:'Keep temperature in the conversation.', description:'Build visibility around temperature-sensitive storage and movement, with measurement context and a clear response process.', icon:'cold', points:['Storage and transit monitoring design','Excursion review and notification planning','Measurement history and reporting requirements'], question:'What temperature limits, sampling intervals and records does your process require?'},
 {slug:'smart-facilities', title:'Smart facilities', short:'One building. A more connected picture.', description:'Explore how equipment, rooms and environmental data can support day-to-day facility operations.', icon:'building', points:['Equipment and environmental visibility','Site-level dashboards','Maintenance and operational handoffs'], question:'Which building systems and existing tools need to work together?'},
 {slug:'energy', title:'Energy monitoring', short:'Make consumption easier to understand.', description:'Start with a metering and reporting approach that gives operational teams useful context on energy use.', icon:'energy', points:['Metering scope and data collection','Consumption patterns and comparisons','Reporting and anomaly-review requirements'], question:'Where do you need better visibility into consumption and operating hours?'},
 {slug:'integration', title:'Integration & data workflows', short:'Connect the reading to the next step.', description:'Define how device data should reach the right dashboard, system and person, with access and data ownership considered from the start.', icon:'network', points:['Device-to-platform architecture','API and existing-system assessment','Access, retention and operational responsibility'], question:'Where must the data go, and who is responsible for acting on it?'}
] as const;
export const industries = [
 ['Healthcare & laboratories','Equipment location, storage conditions and facilities visibility.','asset-tracking'],
 ['Logistics & cold chain','Movement and environmental context across storage and transit.','cold-chain'],
 ['Buildings & facilities','A clearer view of equipment, spaces and consumption.','smart-facilities'],
 ['Retail & distribution','Connect stock environments, equipment and site operations.','remote-monitoring'],
 ['Energy & infrastructure','Understand operating conditions and resource use.','energy'],
] as const;
export const process = [['Discover','Start with the operational question, the people involved and what useful visibility looks like.'],['Design','Define devices, connectivity, data ownership and integration requirements around the site.'],['Pilot','Test coverage, data quality and workflow assumptions against agreed success criteria.'],['Deploy & support','Agree rollout, training, monitoring responsibilities and ongoing support before scaling.']] as const;
