import './styles.css';
const solutions=[['⌖','Asset Tracking & RTLS','Live location and utilisation visibility for critical assets across rooms, facilities and sites.'],['◉','Remote Monitoring','Continuously monitor temperature, humidity, pressure, power and equipment state.'],['❄','Cold Chain Intelligence','Telemetry, excursion alerts, records and trends for temperature-sensitive operations.'],['▦','Smart Facilities','Connect rooms, equipment, utilities and environmental sensors into one operational view.'],['ϟ','Energy Monitoring','Measure consumption, detect anomalies and understand high-impact energy assets.'],['◇','IoT Security & Compliance','Monitoring, audit trails, controlled access and compliance-minded architecture.']];
const industries=['Healthcare & Laboratories','Pharmaceutical','Logistics & Cold Chain','Retail','Buildings & Facilities','Energy','Smart Infrastructure'];
document.querySelector('#app').innerHTML=`
<header><div class="shell nav"><a class="brand" href="#top"><i></i>LOYDTECH</a><nav><a href="#solutions">Solutions</a><a href="#platform">Sentinel 365</a><a href="#industries">Industries</a><a href="#security">Security</a></nav><a class="btn small" href="#contact">Book a demo ↗</a></div></header>
<main id="top"><section class="hero shell"><div class="hero-copy"><span class="eyebrow">● CONNECTED INTELLIGENCE FOR A SMARTER TOMORROW</span><h1>Connect.<br>Monitor.<br><em>Optimise.</em></h1><p>IoT and digital solutions that give you real-time visibility, control and insight across assets, environments and operations.</p><div class="actions"><a class="btn" href="#contact">Explore a solution ↗</a><a href="#platform">Discover Sentinel 365 →</a></div><div class="meta"><b>RTLS<small>Live asset visibility</small></b><b>IoT<small>Remote monitoring</small></b><b>AI<small>Operational analytics</small></b></div></div>
<div class="visual"><div class="halo"></div><div class="dash glass"><div class="dash-head"><div><small>SENTINEL 365</small><h3>Operations overview</h3></div><span>● LIVE</span></div><div class="metrics"><article><small>CONNECTED ASSETS</small><strong>1,284</strong><i>Illustrative data</i></article><article><small>ACTIVE ALERTS</small><strong>08</strong><i>3 require attention</i></article></div><div class="chart"><span>ENVIRONMENTAL TELEMETRY</span><svg viewBox="0 0 600 170"><path d="M0 145 C55 120 80 132 120 102 S200 65 245 94 S310 118 350 78 S415 40 455 62 S530 82 600 25" /></svg></div><div class="asset"><span>❄ Cold Room A <small>2.8°C · Cape Town Facility</small></span><b>Stable</b></div><div class="asset"><span>⌖ Infusion Pump 042 <small>Level 2 · East Wing</small></span><b>Located</b></div></div></div></section>
<div class="trust"><div class="shell"><span>BUILT FOR CONNECTED ENVIRONMENTS</span><b>HEALTHCARE</b><b>LABS</b><b>PHARMA</b><b>LOGISTICS</b><b>FACILITIES</b></div></div>
<section id="solutions" class="section shell"><div class="heading"><div><span class="kicker">01 / SOLUTIONS</span><h2>One connected layer for your <muted>physical operations.</muted></h2></div><p>From a single sensor to a multi-site deployment, Loydtech brings real-world data into a platform your team can act on.</p></div><div class="cards">${solutions.map((x,i)=>`<article><small>0${i+1}</small><i>${x[0]}</i><h3>${x[1]}</h3><p>${x[2]}</p><a href="#contact">Learn more ↗</a></article>`).join('')}</div></section>
<section id="platform" class="platform"><div class="shell platform-grid"><div><span class="kicker">02 / PLATFORM</span><div class="s365">S365</div><h2>Sentinel 365</h2><h3>Your operational intelligence layer.</h3><p>Live asset location, sensor telemetry, alerts, floor plans, geofences and historical analytics in one interface.</p><ul><li>Live maps & indoor asset visibility</li><li>Device telemetry & condition monitoring</li><li>Rules, alerts & escalation workflows</li><li>Historical trends & operational reporting</li><li>API-ready integrations & automation</li></ul></div><div class="map glass"><div class="zone z1">LAB 01</div><div class="zone z2">COLD ROOM</div><div class="zone z3">STORES</div><i class="pin p1"></i><i class="pin p2"></i><i class="pin p3"></i></div></div></section>
<section id="industries" class="section shell"><div class="heading"><div><span class="kicker">03 / INDUSTRIES</span><h2>Designed for places where <muted>visibility matters.</muted></h2></div></div><div class="industries">${industries.map((x,i)=>`<div><span>0${i+1}</span><strong>${x}</strong><i>↗</i></div>`).join('')}</div></section>
<section class="section shell"><div class="heading"><div><span class="kicker">04 / HOW IT WORKS</span><h2>From physical asset to <muted>actionable insight.</muted></h2></div></div><div class="steps"><article><span>01</span><h3>Connect</h3><p>Sensors, tags, gateways and equipment feed operational data securely.</p></article><article><span>02</span><h3>Monitor</h3><p>Sentinel 365 brings device state, environment and location into one live view.</p></article><article><span>03</span><h3>Automate</h3><p>Rules trigger alerts, workflows and integrations when conditions change.</p></article><article><span>04</span><h3>Optimise</h3><p>Historical trends reveal opportunities to improve performance.</p></article></div></section>
<section class="about"><div class="shell about-grid"><div><span class="kicker">05 / LOYDTECH</span><h2>People. Technology.<br><em>A smarter tomorrow.</em></h2><p>Loydtech Digital Solutions connects physical operations to useful digital intelligence through field knowledge, connected devices, cloud platforms and automation.</p></div><div class="glass process"><div><b>01</b>Discover the operational need</div><div><b>02</b>Design the device-to-cloud architecture</div><div><b>03</b>Deploy, integrate and validate</div><div><b>04</b>Monitor, automate and improve</div></div></div></section>
<section id="security" class="section shell"><div class="heading"><div><span class="kicker">06 / TRUST</span><h2>Secure by design. <muted>Ready for regulated environments.</muted></h2></div><p>Layered security, controlled access, auditability and integration are designed into connected operations.</p></div><div class="eco"><article><span>01</span><h3>Security monitoring</h3><p>Visibility across connected infrastructure and operational events.</p></article><article><span>02</span><h3>Access & audit</h3><p>Role-aware visibility and auditable system activity.</p></article><article><span>03</span><h3>Compliance-minded</h3><p>Architecture aligned to POPIA and common information-security controls.</p></article><article><span>04</span><h3>Integration-ready</h3><p>Connect automation, cloud and security platforms.</p></article></div></section>
<section class="section shell"><div class="heading"><div><span class="kicker">07 / ECOSYSTEM</span><h2>Built to work across your <muted>technology stack.</muted></h2></div></div><div class="ribbon"><span>Microsoft Azure</span><span>Cisco</span><span>Milesight</span><span>Minew</span><span>ThingsBoard</span><span>n8n</span><span>Wazuh</span><span>Splunk</span></div></section>
<section id="contact" class="cta shell"><div><span class="kicker">08 / START A PROJECT</span><h2>Turn physical operations into <em>live intelligence.</em></h2></div><div><p>Tell us what you need to track, monitor or optimise. We'll help shape the connected solution.</p><a class="btn" href="mailto:info@loydtech.co.za">Start a conversation ↗</a></div></section></main>
<footer><div class="shell"><b>LOYDTECH DIGITAL SOLUTIONS</b><span>IoT · RTLS · Remote Monitoring · Analytics</span><span>South Africa · Connected everywhere.</span></div></footer>`;
